import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Text, Flex } from '@chakra-ui/react'
import { useRouter } from 'next/router'

const Home: NextPage = () => {
 const router = useRouter()
 return (
  <Box maxW="container.md" mx="auto" p={8}>
   <Head>
    <title>Create Ref Link</title>
    <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
    <link href="/favicon.ico" rel="icon" />
   </Head>

   <Text mb={4}>Post: {router.query.campaign}</Text>

   <Flex direction="column" mt={8}>
    {/* Main content goes here */}
   </Flex>
  </Box>
 )
}

export default Home
